### ISSUE TITLE
API

### ISSUE THREAD

**Issue by enderahmetyurt** [yusufcakmak/topluluk-rehberi#19]
Bütün bu bilgileri bir API yapsak belki birkaç app yazabiliriz. Toplu bir uygulamada da bulunmuş olur.

**Comment by yusufcakmak** [comment]
@enderahmetyurt güzel bir hareket olabilir. issue'yu açık bırakıyorum, belki desteklemek isteyenler veya farklı fikirde olanlar çıkabilir.
