### ISSUE TITLE
Toplulukların kategorize edilmesi

### ISSUE THREAD

**Issue by yusufcakmak** [yusufcakmak/topluluk-rehberi#35]
İçeriğin daha düzenli ve kolay erişilebilir olması adına kategori sistemi uygulanabilir gibi geliyor. Üniversite toplulukları ayrı bir dizine alınabilir, şehirlere ayrılabilir, gdg & wtm ayrı bir dizine alınabilir veya kategorilere ayrılabilir.  Aklıma gelen seçenekler bunlar. Bu konu ile ilgili fikir belirtmek isteyen olursa ona göre düzenleyebiliriz.

Aşağıdaki GDG Istanbul reposunda konulara göre kategori ayrımı yapılmıştı. İçeriğe ulaşımı kolaylaştırıyor.

https://github.com/gdgistanbul/awesome-presentations

**Comment by lemiorhan** [comment]
Çok mantıklı. Senin fikirlerini şu şekilde destekleyebilirim.

- Her bir topluluğa ayrı bir sayfa olmalı. 
  - Bu sayfanın bir şablonu ayrı bir "topluluk-sayfası-sablonu" şeklinde durmalı ve tüm topluluklar bu şablondan kendi sayfalarını oluşturmalı. Bu şablon kısıtlayıcı değil, aksine çok daha fazla bilginin girilebilmesine olanak tanımalı. 
- Ana readme'de sınıflandırma yapılabilir. Bu sınıflandırma bir matris/tablo şeklinde tutulabilir. Yani örnek vermek gerekirse, tablo içindeki başlıklar topluluk adı, meetup frekansı, meetup mekanı, meetup linki vs barındırabileceği gibi, topluluk dalı (community branch) ya da üniversite topluluğu gibi ana başlıkarda da olabilir.

Şimdilik aklıma gelen fikirler bu şekilde. Çok kolay gelsin.

**Comment by yusufcakmak** [comment]
Desteğin için teşekkür ederim,  çok güzel geri bildirim oldu.

Branch açıp üzerine çalışabiliriz. Topluluk sayfası şablonu ve ana readme üzerine çalışıp, seni haberdar edebilirim. Böylece farklı bir fikir oluşursa onuda uygulamak için şansımız olur.

**Comment by yusufcakmak** [comment]
@msusur json veya yml hangisini tercih edersen sağlayabilirim :) bir adım öteye taşıma konusunda yardımcı da olmak isterim.

**Comment by msusur** [comment]
JSON mantikli geliyor, sonrasinda nodejs ile bir graphql API olusturabiliriz. Bir toplulugun nasil ozellikleri olmali? Aklinda bir liste var mi? Onerim soyle

```json
[
  {
    "name": 'string',
    "description": 'string',
    "addedBy": 'string',
    "links": [
      { "twitter": 'string', "description": 'string' },
      { "facebook": 'string', "description": 'string' }
    ],
    "logo": "string",
    "type": "string" // Podcast || video || meetup || working group?
  }
]
```

**Comment by yusufcakmak** [comment]
Yukarıdaki bilgilerin dışında meetup linki önemli olabilir, tabiki kolaylaştırır. Slack gibi bir açık iletişim kanalı varsa onu ekleyebiliriz. Topluluk katılımı kontrollü olarak yapıyorsa bu kuralların olduğu bir kaynak veya katılım formu gibi bir link, katılmak isteyenler için çok faydalı olacaktır.

Meetup
Slack (iletişim kanalı)
Katılım Formu (websites, googleform vs)

**Comment by msusur** [comment]
o zaman bu issue kapsaminda yapmamiz gerekenler;

1. Elimizdeki listeyi simdilik bu format ile baslayip bir json dosyasinda toplamak
2. Readme'yi update edip bu formati aciklamak

yeterli mi? Yukarida @lemiorhan 'in bahsettigi konuyu belki yeni bir issue olarak degerlendirip #19 API den sonra hemen otomatik yapabiliriz. Ya da API'ye gerek duymadan autogenerate de edilebilir sanirim. O zaman cok daha tatli ve hizli olur belki.

**Comment by yusufcakmak** [comment]
Bu format yeterli gibi şimdilik, eksiklik fark edersek daha sonra da doldurabiliriz. dediğin gibi @lemiorhan ın önerisini issue olarak alıp, api den sonra bakabiliriz.

**Comment by mehmetkose** [comment]
aslında içerik markdown olarak kalsa, hem github üzerinde görüntülenebiliyor olur, hem de react, vue gibi şeyler parse edip sunabilir olur, diye düşünüyorum.

**Comment by msusur** [comment]
anladigim kadariyla @lemiorhan 'in onerisi bunu bir template kullanarak autogenerate etmek. Bu yuzden api mantikli geldi bana
